site_name: NIWC Pacific Unmanned Systems and Robotics Publications
site_url: https://RoboPubs.github.io/Publications
site_description: An archive of unmanned systems and robotics papers from U.S. Navy Information Warfare Center (NIWC) Pacific

repo_name: RoboPubs/Publications
repo_url: https://github.com/RoboPubs/Publications

theme: material

markdown_extensions:
  - pymdownx.details

pages:
  - 2010-2019: 'index.md'
  - 2000-2009: '2000.md'
  - 1990-1999: '1990.md'
  - 1980-1989: '1980.md'
